from __future__ import annotations

import json
import subprocess
import uuid
from pathlib import Path

import pytest

from pcae.core.paths import HarnessPath
from pcae.core.repository_identity import (
    REPOSITORY_IDENTITY_RELATIVE_PATH,
    RepositoryIdentityMalformedError,
    RepositoryIdentitySymlinkError,
    ensure_repository_identity,
    read_repository_identity,
)


def _root(tmp_path: Path) -> HarnessPath:
    return HarnessPath(tmp_path)


def _identity_path(tmp_path: Path) -> Path:
    return tmp_path / REPOSITORY_IDENTITY_RELATIVE_PATH


def test_read_missing_identity_returns_none(tmp_path: Path) -> None:
    assert read_repository_identity(_root(tmp_path)) is None


def test_ensure_creates_valid_identity(tmp_path: Path) -> None:
    identity = ensure_repository_identity(_root(tmp_path))

    assert identity.schema_version == 1
    parsed = uuid.UUID(identity.repository_instance_id)
    assert parsed.version == 4
    assert _identity_path(tmp_path).exists()

    on_disk = json.loads(_identity_path(tmp_path).read_text(encoding="utf-8"))
    assert on_disk == identity.to_dict()


def test_ensure_is_idempotent(tmp_path: Path) -> None:
    first = ensure_repository_identity(_root(tmp_path))
    second = ensure_repository_identity(_root(tmp_path))

    assert first == second
    assert read_repository_identity(_root(tmp_path)) == first


def test_missing_and_malformed_are_distinct_outcomes(tmp_path: Path) -> None:
    path = _identity_path(tmp_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("not json", encoding="utf-8")

    with pytest.raises(RepositoryIdentityMalformedError):
        read_repository_identity(_root(tmp_path))

    # Malformed is never silently auto-regenerated by ensure().
    with pytest.raises(RepositoryIdentityMalformedError):
        ensure_repository_identity(_root(tmp_path))
    assert path.read_text(encoding="utf-8") == "not json"


def test_unknown_schema_version_rejected(tmp_path: Path) -> None:
    path = _identity_path(tmp_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps({"schema_version": 999, "repository_instance_id": str(uuid.uuid4()), "created_at": "2026-08-05T00:00:00.000Z"}),
        encoding="utf-8",
    )

    with pytest.raises(RepositoryIdentityMalformedError):
        read_repository_identity(_root(tmp_path))


def test_unrecognized_field_rejected(tmp_path: Path) -> None:
    path = _identity_path(tmp_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "repository_instance_id": str(uuid.uuid4()),
                "created_at": "2026-08-05T00:00:00.000Z",
                "trusted": True,
            }
        ),
        encoding="utf-8",
    )

    with pytest.raises(RepositoryIdentityMalformedError):
        read_repository_identity(_root(tmp_path))


def test_non_uuid4_identifier_rejected(tmp_path: Path) -> None:
    path = _identity_path(tmp_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps({"schema_version": 1, "repository_instance_id": "not-a-uuid", "created_at": "2026-08-05T00:00:00.000Z"}),
        encoding="utf-8",
    )

    with pytest.raises(RepositoryIdentityMalformedError):
        read_repository_identity(_root(tmp_path))


def test_naive_timestamp_rejected(tmp_path: Path) -> None:
    path = _identity_path(tmp_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps({"schema_version": 1, "repository_instance_id": str(uuid.uuid4()), "created_at": "2026-08-05T00:00:00"}),
        encoding="utf-8",
    )

    with pytest.raises(RepositoryIdentityMalformedError):
        read_repository_identity(_root(tmp_path))


def test_symlinked_identity_file_rejected(tmp_path: Path) -> None:
    path = _identity_path(tmp_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    decoy = tmp_path / "decoy.json"
    decoy.write_text(
        json.dumps({"schema_version": 1, "repository_instance_id": str(uuid.uuid4()), "created_at": "2026-08-05T00:00:00.000Z"}),
        encoding="utf-8",
    )
    path.symlink_to(decoy)

    with pytest.raises(RepositoryIdentitySymlinkError):
        read_repository_identity(_root(tmp_path))
    with pytest.raises(RepositoryIdentitySymlinkError):
        ensure_repository_identity(_root(tmp_path))


def test_path_move_preserves_identity(tmp_path: Path) -> None:
    original_root = tmp_path / "original"
    original_root.mkdir()
    identity = ensure_repository_identity(_root(original_root))

    moved_root = tmp_path / "moved"
    original_root.rename(moved_root)

    reread = read_repository_identity(_root(moved_root))
    assert reread == identity


def test_full_directory_copy_confers_no_authority_by_itself(tmp_path: Path) -> None:
    """This module has no concept of authority at all -- copying the
    identity file changes nothing except that a second deployment now
    also has a repository_instance_id on disk. Layer 2 (hatp_bootstrap.py)
    is what refuses to honor it without a matching deployment binding."""

    import shutil

    repo_a = tmp_path / "repo-a"
    repo_a.mkdir()
    identity_a = ensure_repository_identity(_root(repo_a))

    repo_b = tmp_path / "repo-b"
    shutil.copytree(repo_a, repo_b)

    identity_b = read_repository_identity(_root(repo_b))
    assert identity_b == identity_a
    # No authority concept exists in this module to assert on; the
    # absence of any such API is itself the guarantee (HATP-REQ-051).
    import pcae.core.repository_identity as ri_module

    assert not hasattr(ri_module, "authority")
    assert not any("authority" in name.lower() for name in dir(ri_module) if not name.startswith("_"))


def test_manual_mutation_is_syntactically_validated_only(tmp_path: Path) -> None:
    root = _root(tmp_path)
    ensure_repository_identity(root)

    new_id = str(uuid.uuid4())
    path = _identity_path(tmp_path)
    document = json.loads(path.read_text(encoding="utf-8"))
    document["repository_instance_id"] = new_id
    path.write_text(json.dumps(document), encoding="utf-8")

    reread = read_repository_identity(root)
    assert reread is not None
    assert reread.repository_instance_id == new_id


def test_no_caller_supplied_trust_override_parameter() -> None:
    import inspect

    from pcae.core import repository_identity as ri_module

    sig = inspect.signature(ri_module.read_repository_identity)
    assert "trusted_id" not in sig.parameters
    assert "trusted" not in sig.parameters
    sig_ensure = inspect.signature(ri_module.ensure_repository_identity)
    assert "trusted_id" not in sig_ensure.parameters


@pytest.mark.skipif(
    subprocess.run(["git", "--version"], capture_output=True).returncode != 0,
    reason="git is not available",
)
def test_worktree_receives_distinct_repository_identity(tmp_path: Path) -> None:
    main_repo = tmp_path / "main-repo"
    main_repo.mkdir()
    subprocess.run(["git", "init"], cwd=main_repo, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=main_repo, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=main_repo, check=True, capture_output=True)
    (main_repo / "README.md").write_text("root\n", encoding="utf-8")
    subprocess.run(["git", "add", "README.md"], cwd=main_repo, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-m", "initial"], cwd=main_repo, check=True, capture_output=True)

    identity_main = ensure_repository_identity(_root(main_repo))

    worktree_dir = tmp_path / "worktree-a"
    subprocess.run(
        ["git", "worktree", "add", "-b", "worktree-branch", str(worktree_dir)],
        cwd=main_repo,
        check=True,
        capture_output=True,
    )

    assert read_repository_identity(_root(worktree_dir)) is None
    identity_worktree = ensure_repository_identity(_root(worktree_dir))

    assert identity_worktree.repository_instance_id != identity_main.repository_instance_id
